name: Build Mac App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4  # 升级到了 v4

    - name: Set up Python
      uses: actions/setup-python@v5  # 升级到了 v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        # 注意：Mac下不用加 -w，否则 input() 无法输入
        pyinstaller -F main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4  # 【关键修复】升级到了 v4
      with:
        name: mac-app-executable
        path: dist/auto_sender_mac
